version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection.json
          environment: ./env.json
workflows:
  version: 2

  build-and-trigger:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
