version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run-newman-tests:
          name: Run Newman Tests
          command: newman/newman-run
          args:
            collection: ./collection.json
            environment: ./env.json
workflows:
  version: 2
  build-and-test:
    jobs:
      - build